name: filrouge
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./config/postgres:/etc/postgres/conf.d
      # - ~/volumes/jhipster/nouveauDossier/postgres/:/var/lib/postgres/data/
    environment:
      - POSTGRES_DB=filRouge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nouhailakhaouti1...
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "filrouge", "-t", "1"]
      interval: 5s
      timeout: 5s
      retries: 10
  sonar:
    container_name: sonarqube_filRouge
    image: sonarqube:10.3.0-community
    # Forced authentication redirect for UI is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete SONAR_FORCEAUTHENTICATION variable or set SONAR_FORCEAUTHENTICATION=true
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_local
      DB_USER: nouhaila
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8081:8081
    depends_on:
      - postgres